name: Build Common project
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
