name: Deploy
on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      env:
        required: true
        type: string
      arg:
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.env }} --token=${{ secrets.token }}
      - name: Build Project Artifacts
        run: vercel build ${{ inputs.arg }} --token=${{ secrets.token }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt ${{ inputs.arg }} --token=${{ secrets.token }}
