name: DEV actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.template.yml
    with:
      server_url: ${{ vars.SERVER_URL_DEV }}
      cli_username: ${{ vars.CLI_USERNAME }}
    secrets:
      cli_password: ${{ secrets.CLI_PASSWORD }}
      render_api_key: ${{ secrets.RENDER_API_KEY_DEV }}
      render_service_id: ${{ secrets.SERVICE_ID_DEV }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
