name: Develop actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  common-integrity:
    uses: ./.github/workflows/integrity.template.yml
    with:
      dir: ./common
  server-integrity:
    needs: common-integrity
    uses: ./.github/workflows/integrity.template.yml
    with:
      dir: ./server
  astro-integrity:
    needs: common-integrity
    uses: ./.github/workflows/integrity.template.yml
    with:
      dir: ./web
  server-preview:
    needs: server-integrity
    uses: ./.github/workflows/deploy.server.template.yml
    secrets:
      render_api_key: ${{ secrets.RENDER_API_KEY_DEV }}
      service_id: ${{ secrets.SERVICE_ID_DEV }}
  preview:
    needs: [server-preview, astro-integrity]
    uses: ./.github/workflows/deploy.web.template.yml
    with:
      env: preview
    secrets:
      token: ${{ secrets.VERCEL_TOKEN }}
