name: Develop actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  common-integrity:
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./common
  server-integrity:
    needs: common-integrity
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./server
  astro-integrity:
    needs: server-integrity
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./web
  preview:
    needs: astro-integrity
    uses: ./.github/workflows/deploy.web.template.yml
    with:
      env: preview
    secrets:
      token: ${{ secrets.VERCEL_TOKEN }}
