name: Develop actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  integrity:
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./web
  preview:
    needs: integrity
    uses: ./.github/workflows/deploy.web.template.yml
    with:
      env: preview
    secrets:
      token: ${{ secrets.VERCEL_TOKEN }}
