name: Build
on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Get changed files
        id: changed-files-{{ inputs.dir }}
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ inputs.dir }}
      - name: Install
        if: steps.changed-files-${{ inputs.dir }}.outpus.any_changed == 'true'
        run: npm ci
      - name: Lint
        if: steps.changed-files-${{ inputs.dir }}.outpus.any_changed == 'true'
        run: npm run lint
      - name: Test
        if: steps.changed-files-${{ inputs.dir }}.outpus.any_changed == 'true'
        run: npm run test
