name: Production actions
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  common-integrity:
    uses: ./.github/workflows/build.common.template.yml
  server-integrity:
    needs: common-integrity
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./server
  astro-integrity:
    needs: common-integrity
    uses: ./.github/workflows/build.template.yml
    with:
      dir: ./web
  production:
    needs: [server-integrity, astro-integrity]
    uses: ./.github/workflows/deploy.web.template.yml
    with:
      env: production
      arg: --prod
    secrets:
      token: ${{ secrets.VERCEL_TOKEN }}
